# This is a basic workflow to help you get started with Actions

name: OneFLOW_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest]  
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run echo Hello, world!
        run: echo "Hello, world!"   

      # Runs a single command using the runners shell
      - name: Print system info
        run: |
          echo $PATH
          node -v
          npm -v
          python --version
          java --version
          go version
          mvn -version
          docker version
          docker-compose -v
          git version
      