# This is a basic workflow to help you get started with Actions

name: OneFLOW_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}  
    strategy:
      matrix:
        config:
        - {
            name: "Windows OneFLOW CFD",
            os: windows-latest,
            prefix : "C:/Program Files (x86)/CMakePrj/",            
            #prefix : "C:/Program Files (x86)/",            
          }
        - {
            name: "Ubuntu OneFLOW CFD",
            os: ubuntu-latest,
            prefix : "/usr/local/CMakePrj/",            
          }        
    steps:
      - uses: actions/checkout@v2
      
      - name: Display the path by pwsh
        run: echo ${env:PATH}
        shell: pwsh  
      - name: Display github.workspace by pwsh
        run: |
          echo "github.workspace is ${{ github.workspace }}."  
          ls ${{ github.workspace }}
        shell: pwsh
      - name: Display cd github.workspace by pwsh
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir build
          cd build
          cmake --version
          cmake ../
          ls
        shell: pwsh
