# This is a basic workflow to help you get started with Actions

name: OneFLOW_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Windows OneFLOW CFD build"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display the path by pwsh
        run: echo ${env:PATH}
        shell: pwsh  
      - name: Display github.workspace by pwsh
        run: |
          echo "github.workspace is ${{ github.workspace }}."  
          ls ${{ github.workspace }}
        shell: pwsh
      - name: CMake Build
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir build
          cd build
          cmake --version
          cmake ../
          ls
        shell: pwsh
      - name: CMake Install
        env:
          prefix: "C:/Program Files (x86)/CMakePrj/"
        run: |
          cd ${{ github.workspace }}/build
          ls
          cmake --build . --target INSTALL --config release
          ls "${{env.prefix}}"
          cd "${{env.prefix}}bin"
          ls
          "${{env.prefix}}bin/"CMakePrj.exe
        shell: pwsh