# This is a basic workflow to help you get started with Actions

name: OneFLOW_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: "Windows OneFLOW CFD build"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display the path by pwsh
        run: echo ${env:PATH}
        shell: pwsh  
      - name: Display github.workspace by pwsh
        run: |
          echo "github.workspace is ${{ github.workspace }}."  
          ls ${{ github.workspace }}
        shell: pwsh
      - name: CMake Build
        run: |
          cd ${{ github.workspace }}
          ls
          mkdir build
          cd build
          cmake --version
          cmake ../
          ls
        shell: pwsh
  install:
    needs: build
    name: "Windows OneFLOW CFD install"
    runs-on: windows-latest
    steps:
      - name: CMake Install
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.  
          echo ${{MY_VAR}}
          echo "${{MY_VAR}}"
        shell: pwsh
